### ISSUE TITLE
Get Footstep Sounds From Files

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/Treachery-Old#34]
Sound files need to be extracted from the raw footstep/jump sounds. In the sounds/footsteps/raw folder, sound needs to be taken from the  raw files. 

As of writing the issue, only hardwood and concrete have been extracted. There is still many more to do. Sound should be extracted by looking at the raw file, searching for footstep, jump and land sound portions and cutting these out into new files with a program like Audacity. 

Here is a list of the sound groups and files that still need to be completed:

* Carpet
  * Files: Carpet Jump-land.mp3, Carpet Walk 2.mp3, Carpet Walk.mp3
* Dirt
  * Files: Dirt Walk.mpy, Dirt Jump.mp3
* Grass
  * Files: Grass Jump.mp3 , Grass Walk.mp3, Grass Walk 2.mp3
* Gravel
  * Files: Gravel Jump.mp3, Gravel Walk.mp3
* Mulch
  * Files: Mulch Jump.mp3, Mulch walk.mp3

**Comment by nicholas-maltbie** [comment]
Now need to add these to a specific player for testing.

**Comment by assafen** [comment]
Footstep files are extracted.
